class PartnersController < ApplicationController
  def index
    @partners = [
      {name:'wri', image:'partners/wri.png', url:'partners/wri', description: "The World Resources Institute (WRI) is a global research organization that spans more than 50 countries. We convene over 450 experts to work closely with leaders to turn big ideas into actions that sustain our natural resources—the foundation of economic opportunity and human well-being."},
      {name:'vizzuality', image:'partners/vizzuality@2x.png', url:'partners/vizzuality', description: "Vizzuality is a world-renowned digital agency, delivering bespoke, beautiful visualisations and tools to the most important organisations in the world. Pushing the boundaries of how data is stored, shared and visualised, we help to improve our world one visualisation at a time."},
      {name:'google', image:'partners/google@2x.png', url:'partners/google', description: "Google Earth Engine brings together the world's satellite imagery and makes it available online alongside tools for scientists, independent researchers and nations to mine this massive warehouse of data."},
      {name:'cartodb', image:'partners/cartodb@2x.png', url:'partners/cartodb', description: "The easiest way to make maps online. Since launching in 2012 over 130,000 people have used it to create data-driven maps, which enable visual discovery of trends and patterns, and make better, faster decisions."},
      {name:'digitalglobe', image:'partners/digitalglobe@2x.png', url:'partners/digitalglobe', description: "DigitalGlobe is a leading provider of high‑resolution Earth imagery products and services. Sourced from our own advanced satellite constellation, our imagery solutions support a wide variety of uses, including environmental monitoring."},
      {name:'earthgenome', image:'partners/earthgenome@2x.png', url:'partners/earthgenome', description: "The Earth Genome is enabling the world's key institutions to fully account for natural capital in all their decisions. We are connecting the world's best earth data, scientists, and technology providers to drive insight and innovation for governments, NGOs, corporations, and investors."},
      {name:'descarteslabs', image:'partners/descarteslabs@2x.png', url:'partners/descarteslabs', description: "Our mission is to better understand planet Earth by analyzing massive amounts of imagery. We’ll begin this journey by understanding satellite imagery to enable real-time global awareness — whether it’s food production, energy infrastructure, the growth of cities, or our impact on the environment. Not only will we identify what’s in a single image, but we’ll also be looking at how our Earth changes over time."}
    ]
  end
end
